spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/verysimplesns
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB

file:
  upload-dir: uploads